### ISSUE TITLE
Update new version with PS 0.11 compatible update

### ISSUE THREAD

**Issue by hgiasac** [epost/purescript-node-postgres#16]
Hello,

I make a pull request to add this repo into psc-package's [package-sets
](https://github.com/purescript/package-sets/pull/103#issue-257350679). Because you have not updated new version with PS 0.11 compatibility, the Travis test was failed

Can you update tag for new version?
Thanks

**Comment by anttih** [comment]
There is now a 3.0.0. Thanks!
